spring:
    profiles:
      active: @profiles_active@
mapway:
    apidoc:
        enabled: true
        url: /doc/*
        author: jyzhangbo@gmail.com
        copyright: zhangbo
        title: springboot学习
        subTitle: springboot
        scans: com.github.jyzhangbo
